---
- hosts: all
  tasks:
    - name: Pull git repos
      git: repo={{ item.repo }} dest={{ item.dest }}
      with_items:
        - repo: git@github.com:emilyhorsman/dotfiles.git
          dest: ~/.dotfiles
        - repo: https://github.com/tyrannicaltoucan/vim-deep-space.git
          dest: ~/.dotfiles/deep-space
        - repo: https://github.com/emilyhorsman/tomorrow-theme.git
          dest: ~/.dotfiles/tomorrow
        - repo: https://github.com/tmux-plugins/tpm
          dest: ~/.tmux/plugins/tpm
        - repo: https://github.com/facebook/PathPicker.git
          dest: ~/.dotfiles/fpp
    - name: Make directories
      file: state=directory path={{ item }}
      with_items:
        - ~/.config/nvim/colors
        - ~/.config/nvim/autoload
        - ~/.vim/autoload
        - ~/.vim/colors
        - ~/bin
    - name: Download vim plugged
      get_url:
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: ~/.config/nvim/autoload/plug.vim
    - name: Link config files
      file: src={{ item.src }} dest={{ item.dest }} state=link
      with_items:
        - { src: '~/.dotfiles/zshrc', dest: '~/.zshrc' }
        - { src: '~/.dotfiles/vimrc', dest: '~/.vimrc' }
        - { src: '~/.dotfiles/tmux.conf', dest: '~/.tmux.conf' }
        - { src: '~/.dotfiles/gitconfig', dest: '~/.gitconfig' }
        - { src: '~/.dotfiles/tomorrow/vim/colors/Tomorrow-Night.vim', dest: '~/.vim/colors/Tomorrow-Night.vim' }
        - { src: '~/.dotfiles/deep-space/colors/colors/deep-space.vim', dest: '~/.config/nvim/colors/deep-space.vim' }
        - { src: '~/.dotfiles/bin/tmux-vim-select-pane', dest: '~/bin/tmux-vim-select-pane' }
        - { src: '~/.dotfiles/fpp/fpp', dest: '~/bin/fpp' }
