---
- hosts: all
  tasks:
    - name: Pull git repos
      git: repo={{ item.repo }} dest={{ item.dest }}
      with_items:
        - repo: https://github.com/emilyhorsman/dotfiles.git
          dest: ~/.dotfiles
        - repo: https://github.com/emilyhorsman/tomorrow-theme.git
          dest: ~/.dotfiles/tomorrow
        - repo: https://github.com/tmux-plugins/tpm
          dest: ~/.tmux/plugins/tpm
    - name: Make directories
      file: state=directory path={{ item }}
      with_items:
        - ~/.config/nvim/colors
        - ~/.config/nvim/autoload
        - ~/.config/fish
        - ~/.config/sway
        - ~/bin
    - name: Download vim plugged
      get_url:
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: ~/.config/nvim/autoload/plug.vim
    - name: Link config files
      file: src={{ item.src }} dest={{ item.dest }} state=link
      with_items:
        - { src: '~/.dotfiles/config.fish', dest: '~/.config/fish/config.fish' }
        - { src: '~/.dotfiles/init.vim', dest: '~/.config/nvim/init.vim' }
        - { src: '~/.dotfiles/config.sway', dest: '~/.config/sway/config' }
        - { src: '~/.dotfiles/zshrc', dest: '~/.zshrc' }
        - { src: '~/.dotfiles/vimrc', dest: '~/.vimrc' }
        - { src: '~/.dotfiles/tmux.conf', dest: '~/.tmux.conf' }
        - { src: '~/.dotfiles/gitconfig', dest: '~/.gitconfig' }
        - { src: '~/.dotfiles/bin/tmux-vim-select-pane', dest: '~/bin/tmux-vim-select-pane' }
