set -g default-shell /usr/local/bin/fish
set -sg escape-time 10
set -g default-terminal "xterm-256color"
set -g -a terminal-overrides ',*:Ss=\E[%p1%d q:Se=\E[2 q:tmux-256color:Tc'


# ^f prefix
set -g prefix C-f

set -g xterm-keys on

# Bring back clear screen under tmux prefix
bind C-l send-keys 'C-l'

set -g status-style "fg=magenta"

# tmux >= 2.1
# old options were mode-mouse, mouse-select-pane, mouse-select-window
set -g mouse on

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind up resize-pane -U 5
bind down resize-pane -D 5
bind left resize-pane -L 5
bind right resize-pane -R 5

# Plugins!!

set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-logging'
set -g @plugin 'tmux-plugins/tmux-fpp'
set -g @plugin 'tmux-plugins/tmux-urlview'
set -g @plugin 'nhdaly/tmux-scroll-copy-mode'

run '~/.tmux/plugins/tpm/tpm'
